import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service - Deal Decoder'
};

export default function TermsOfServicePage() {
  return (
    <main className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <h1 className="text-3xl font-extrabold bg-gradient-to-r from-violet-600 to-pink-500 bg-clip-text text-transparent mb-2">
        Terms of Service
      </h1>
      <p className="text-sm text-gray-500 mb-10">Last updated: September 20, 2026</p>

      <div className="space-y-8 text-gray-700 leading-relaxed">
        <section>
          <p>
            These Terms of Service ("Terms") govern your use of UGC Deal
            Decoder ("Deal Decoder," "we," "us"). By creating an account or
            using Deal Decoder, you agree to these Terms. If you don&apos;t agree,
            please don&apos;t use the app.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-3">
            What Deal Decoder does
          </h2>
          <p>
            Deal Decoder lets you paste a brand deal offer, DM, or contract
            and get an AI-generated read on whether the pay is fair, how
            risky the usage-rights terms are, and a suggested counter-offer
            and counter-message. It is a tool to help inform your own
            negotiation — see the "AI disclaimer" section below.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-3">
            Your account
          </h2>
          <p>
            You need an account to use Deal Decoder. You&apos;re responsible for
            keeping your login credentials secure and for all activity under
            your account. Let us know right away if you think your account
            has been compromised.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-3">
            Acceptable use
          </h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-6 space-y-2 mt-2">
            <li>Use Deal Decoder for anything illegal or fraudulent.</li>
            <li>
              Submit content you don&apos;t have the right to share, or that
              violates someone else&apos;s privacy or intellectual property
              rights.
            </li>
            <li>
              Attempt to disrupt, reverse-engineer, or abuse the app or its
              underlying services (including excessive automated requests).
            </li>
            <li>
              Use the app to generate content intended to harass, deceive, or
              harm others.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-3">
            Your content
          </h2>
          <p>
            You retain ownership of the offer text, deal details, and any
            other content you submit. By submitting it, you give us
            permission to process it (including sending it to OpenAI&apos;s API,
            as described in our{' '}
            <Link href="/privacy" className="text-violet-600 hover:underline">
              Privacy Policy
            </Link>
            ) solely to provide the analysis and counter-message you
            requested, and to store your decode history so you can view it
            later.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-3">
            Plans, free usage, and billing
          </h2>
          <p>
            Deal Decoder offers a limited number of free deal decodes per
            account. Paid plans, if you choose one, are billed and processed
            through Stripe on a recurring basis until you cancel. You can
            manage or cancel your subscription at any time from your account
            settings.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-3">
            AI disclaimer
          </h2>
          <p>
            Deal Decoder&apos;s verdicts, fairness scores, market value estimates,
            recommended counter-offers, and counter-messages are generated by
            an AI model based on the information you provide. AI-generated
            output can be incorrect, incomplete, or not applicable to your
            specific circumstances. It is provided for general informational
            purposes only and does{' '}
            <strong>not</strong> constitute legal, financial, tax, or other
            professional advice. You are solely responsible for any decisions
            you make or messages you send based on this output, and we
            recommend consulting a qualified professional for anything with
            real financial or legal consequences.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-3">
            Third-party services
          </h2>
          <p>
            Deal Decoder relies on third-party services to operate, including
            OpenAI (deal analysis), Stripe (payments), Supabase (database
            hosting), and Vercel (hosting and analytics). Your use of Deal
            Decoder is also subject to the availability and terms of these
            underlying services, which are outside our control.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-3">
            No warranty
          </h2>
          <p>
            Deal Decoder is provided "as is" and "as available," without
            warranties of any kind, express or implied, including that the
            app will be uninterrupted, error-free, or that its AI-generated
            output will be accurate.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-3">
            Limitation of liability
          </h2>
          <p>
            To the maximum extent permitted by law, we are not liable for any
            indirect, incidental, or consequential damages arising from your
            use of Deal Decoder, including decisions made or agreements
            entered into based on its output. Our total liability for any
            claim relating to the app is limited to the amount you paid us,
            if any, in the twelve months before the claim.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-3">
            Termination
          </h2>
          <p>
            You may stop using Deal Decoder at any time. We may suspend or
            terminate accounts that violate these Terms. You can request
            deletion of your account and data as described in our{' '}
            <Link href="/privacy" className="text-violet-600 hover:underline">
              Privacy Policy
            </Link>
            .
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-3">
            Changes to these Terms
          </h2>
          <p>
            We may update these Terms from time to time. If we make material
            changes, we&apos;ll update the "Last updated" date above. Continued
            use of Deal Decoder after changes take effect means you accept
            the updated Terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-3">Contact</h2>
          <p>
            Questions about these Terms? Email{' '}
            <a
              href="mailto:devenpurani@gmail.com"
              className="text-violet-600 hover:underline"
            >
              devenpurani@gmail.com
            </a>
            .
          </p>
        </section>
      </div>

      <div className="mt-12">
        <Link href="/" className="text-sm text-violet-600 hover:underline">
          &larr; Back to Deal Decoder
        </Link>
      </div>
    </main>
  );
}
